name: 'Copilot License Automation'
description: 'A GitHub action to automate the licensing of Copilot'
author: 'Dylan Rinker'
inputs:
  daysToDeallocate:
    required: false
    description: 'The number of inactive days which will trigger the deallocation of the Copilot license'
  organization:
    required: false
    description: 'The organization where the Copilot license is allocated'
runs:
  using: 'node16'
  main: 'dist/index.js'
